name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  create: # create branch or tag
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: mirage-synology
      - name: Checkout MirageNetwork/MirageClient
        uses: actions/checkout@v2
        with:
          ref: main
          repository: MirageNetwork/MirageClient
          path: mirage
      - name: make packages
        run: |
          export PATH="${PWD}/mirage/tool:${PATH}"
          cd mirage-synology
          mkdir -p spks
          go run build.go -o spks --source=../mirage --goarch=all --dsm-version=all